### ISSUE TITLE
[FEATURE]: 리쿠르팅 게시물의 아이콘

### ISSUE THREAD

**Issue by otterp012** [SSAF-SOUND/ssaf-sound-fe#37]
### 소개

- 리쿠르팅 페이지에는 6개의 아이콘을 사용합니다.
- 위 아이콘을 재사용가능 및 유지보수 관점에서 작성할 예정입니다.

### 스크린샷

![스크린샷 2023-06-17 오후 8 16 43](https://github.com/SSAF-SOUND/ssaf-sound-fe/assets/87624756/dc5684bc-ed73-4229-ab43-9e72e7ad302c)

**Comment by mjsdo** [comment]
생각해보니까 이거 북마크 아이콘 이런거 말씀하신거 같은데
모든 아이콘 , `components/Icons`같은데에 정리하면 좋을거같네요!
