### ISSUE TITLE
[FEATURE]: Recruit Info 컴포넌트

### ISSUE THREAD

**Issue by otterp012** [SSAF-SOUND/ssaf-sound-fe#56]
### 소개

![스크린샷 2023-06-21 오후 5 26 19](https://github.com/SSAF-SOUND/ssaf-sound-fe/assets/87624756/dfeef184-d8ba-4186-8487-09da45ecd960)

**Comment by mjsdo** [comment]
저 저기있는 기술스택 아이콘이 뭔지 몰라서 일단 `<Icon name="skill" />`에 넣어놨어요.

**Comment by otterp012** [comment]
> 저 저기있는 기술스택 아이콘이 뭔지 몰라서 일단 `<Icon name="skill" />`에 넣어놨어요.

아니 그거 구글 이미지검색해도 안나오네요? 나중에 물어봐야 할듯 일단 얼추 비슷한걸로 넣어둘게요!
